#!/usr/bin/zsh

# extensions / plugins
autoload -Uz compinit promptinit history-search-end
compinit; promptinit
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
source "$HOME"/.local/zsh/fast/fast-syntax-highlighting.plugin.zsh

# prompt
setopt PROMPT_SUBST
function precmd { export LAST_STATUS="$?" }
PROMPT="\$(/home/terry/.config/zsh/prompt.lua)"

# aliases / environment
alias ed="nvim"
alias ip="ip -c"
alias ls="ls --color=auto"
alias pacman="sudo pacman"
alias feh="echo 'you use sxiv now you dolt'; sleep 2; sxiv"
alias salt_the_earth="sudo salt-call --local state.apply"
alias ssh="TERM=xterm-256color ssh"
alias pwgen="pwgen -y 12 4"

export BROWSER=/usr/bin/firefox
export EDITOR=/usr/bin/nvim
export GDK_BACKEND=x11
export GDK_SCALE=2
export PATH="$PATH:$HOME"/.local/bin
export PIPENV_HIDE_EMOJIS=1
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
export VIRTUAL_ENV_DISABLE_PROMPT=1
export WORKON_HOME="$HOME"/.local/venvs
export GOPATH="$HOME/.local/go"

# history
HISTSIZE=65536
SAVEHIST=65536
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups

# bindkeys
bindkey -e
bindkey "^[[A" history-beginning-search-backward-end # UP
bindkey "^[[B" history-beginning-search-forward-end  # DOWN
bindkey "^[[H" beginning-of-line   # HOME
bindkey "^[[F" end-of-line         # END
bindkey "^[[3~" delete-char        # DELETE
